In [1]:
import glob
import argparse
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

evaluation_methods = ['ari', 'nmi', 'purity']
ari_best_result = dict()
nmi_best_result = dict()
purity_best_result = dict()

In [2]:
total = 0
for dirs in glob.glob('mdec_23/*'):
    for em in evaluation_methods:
        with open(dirs + '/' + em + '/total_best_result.txt') as f:
            lines = f.read().splitlines()
            for i, line in enumerate(lines):
                if i == 0: continue
                line = line.split('=')[-1].split(':')
                k, v = line[0].strip(), line[-1].strip()
                if em == 'ari':
                    if k in ari_best_result:
                        ari_best_result[k] += float(v)
                    else:
                        ari_best_result[k] = float(v)
                elif em == 'nmi':
                    if k in nmi_best_result:
                        nmi_best_result[k] += float(v)
                    else:
                        nmi_best_result[k] = float(v)
                else:
                    if k in purity_best_result:
                        purity_best_result[k] += float(v.split('%')[0])
                    else:
                        purity_best_result[k] = float(v.split('%')[0])
    total += 1

In [3]:
for k, v in ari_best_result.items():
    ari_best_result[k] = round(v / total, 3)
for k, v in nmi_best_result.items():
    nmi_best_result[k] = round(v / total, 3)
for k, v in purity_best_result.items():
    purity_best_result[k] = round(v / (total * 100), 3)

print(ari_best_result)
print(nmi_best_result)
print(purity_best_result)

{'jideca_mdecawe_se_23': 0.338, 'jideca_mdecseq2seq_se_23': 0.309, 'jideca_midecawe_re_23': 0.255, 'jideca_mdecseq2seq_re_23': 0.248, 'jideca_mdecawe_re_23': 0.226, 'jideca_midecawe_se_23': 0.239, 'jideca_midecseq2seq_re_23': 0.146, 'jideca_midecseq2seq_se_23': 0.11}
{'jideca_mdecawe_se_23': 0.564, 'jideca_mdecseq2seq_se_23': 0.552, 'jideca_midecawe_se_23': 0.524, 'jideca_mdecseq2seq_re_23': 0.491, 'jideca_mdecawe_re_23': 0.467, 'jideca_midecawe_re_23': 0.461, 'jideca_midecseq2seq_se_23': 0.44, 'jideca_midecseq2seq_re_23': 0.422}
{'jideca_mdecseq2seq_se_23': 0.374, 'jideca_midecawe_re_23': 0.346, 'jideca_mdecawe_se_23': 0.404, 'jideca_midecawe_se_23': 0.342, 'jideca_mdecawe_re_23': 0.27, 'jideca_mdecseq2seq_re_23': 0.28, 'jideca_midecseq2seq_se_23': 0.234, 'jideca_midecseq2seq_re_23': 0.258}

In [4]:
df_ari = pd.DataFrame(list(ari_best_result.items()), columns=['parameters', 'ari'])
df_nmi = pd.DataFrame(list(nmi_best_result.items()), columns=['parameters', 'nmi'])
df_purity = pd.DataFrame(list(purity_best_result.items()), columns=['parameters', 'purity'])
df_nmi

                  parameters    nmi
0       jideca_mdecawe_se_23  0.564
1   jideca_mdecseq2seq_se_23  0.552
2      jideca_midecawe_se_23  0.524
3   jideca_mdecseq2seq_re_23  0.491
4       jideca_mdecawe_re_23  0.467
5      jideca_midecawe_re_23  0.461
6  jideca_midecseq2seq_se_23  0.440
7  jideca_midecseq2seq_re_23  0.422

In [5]:
df_ari

                  parameters    ari
0       jideca_mdecawe_se_23  0.338
1   jideca_mdecseq2seq_se_23  0.309
2      jideca_midecawe_re_23  0.255
3   jideca_mdecseq2seq_re_23  0.248
4       jideca_mdecawe_re_23  0.226
5      jideca_midecawe_se_23  0.239
6  jideca_midecseq2seq_re_23  0.146
7  jideca_midecseq2seq_se_23  0.110

In [6]:
df_purity

                  parameters  purity
0   jideca_mdecseq2seq_se_23   0.374
1      jideca_midecawe_re_23   0.346
2       jideca_mdecawe_se_23   0.404
3      jideca_midecawe_se_23   0.342
4       jideca_mdecawe_re_23   0.270
5   jideca_mdecseq2seq_re_23   0.280
6  jideca_midecseq2seq_se_23   0.234
7  jideca_midecseq2seq_re_23   0.258