In [1]:
import glob
import argparse
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

evaluation_methods = ['ari', 'nmi', 'purity']
ari_best_result = dict()
nmi_best_result = dict()
purity_best_result = dict()

In [2]:
total = 0
for dirs in glob.glob('dec_23/*'):
    for em in evaluation_methods:
        with open(dirs + '/' + em + '/total_best_result.txt') as f:
            lines = f.read().splitlines()
            for i, line in enumerate(lines):
                if i == 0: continue
                line = line.split('=')[-1].split(':')
                k, v = line[0].strip(), line[-1].strip()
                if em == 'ari':
                    if k in ari_best_result:
                        ari_best_result[k] += float(v)
                    else:
                        ari_best_result[k] = float(v)
                elif em == 'nmi':
                    if k in nmi_best_result:
                        nmi_best_result[k] += float(v)
                    else:
                        nmi_best_result[k] = float(v)
                else:
                    if k in purity_best_result:
                        purity_best_result[k] += float(v.split('%')[0])
                    else:
                        purity_best_result[k] = float(v.split('%')[0])
    total += 1

In [3]:
for k, v in ari_best_result.items():
    ari_best_result[k] = round(v / total, 3)
for k, v in nmi_best_result.items():
    nmi_best_result[k] = round(v / total, 3)
for k, v in purity_best_result.items():
    purity_best_result[k] = round(v / (total * 100), 3)

print(ari_best_result)
print(nmi_best_result)
print(purity_best_result)

{'jideca_midec_re_23': 0.275, 'jideca_mdec_se_23': 0.277, 'jideca_idec_se_23': 0.228, 'jideca_mdeca_se_23': 0.239, 'jideca_midec_se_23': 0.23, 'jideca_idec_re_23': 0.224, 'jideca_mdeca_re_23': 0.216, 'jideca_dec_se_23': 0.195, 'jideca_dec_re_23': 0.184, 'jideca_mdec_re_23': 0.099, 'jideca_idec_dnn_23': 0.057, 'jideca_dec_dnn_23': 0.036}
{'jideca_midec_re_23': 0.538, 'jideca_mdec_se_23': 0.512, 'jideca_midec_se_23': 0.493, 'jideca_mdeca_re_23': 0.485, 'jideca_mdeca_se_23': 0.487, 'jideca_idec_se_23': 0.477, 'jideca_idec_re_23': 0.455, 'jideca_dec_se_23': 0.426, 'jideca_dec_re_23': 0.395, 'jideca_mdec_re_23': 0.295, 'jideca_idec_dnn_23': 0.302, 'jideca_dec_dnn_23': 0.299}
{'jideca_idec_se_23': 0.359, 'jideca_mdec_se_23': 0.36, 'jideca_idec_re_23': 0.299, 'jideca_mdeca_se_23': 0.292, 'jideca_midec_re_23': 0.29, 'jideca_dec_se_23': 0.274, 'jideca_dec_re_23': 0.246, 'jideca_mdec_re_23': 0.23, 'jideca_midec_se_23': 0.266, 'jideca_mdeca_re_23': 0.27, 'jideca_idec_dnn_23': 0.19, 'jideca_dec_dnn_23': 0.187}

In [4]:
df_ari = pd.DataFrame(list(ari_best_result.items()), columns=['parameters', 'ari'])
df_nmi = pd.DataFrame(list(nmi_best_result.items()), columns=['parameters', 'nmi'])
df_purity = pd.DataFrame(list(purity_best_result.items()), columns=['parameters', 'purity'])
df_nmi

            parameters    nmi
0   jideca_midec_re_23  0.538
1    jideca_mdec_se_23  0.512
2   jideca_midec_se_23  0.493
3   jideca_mdeca_re_23  0.485
4   jideca_mdeca_se_23  0.487
5    jideca_idec_se_23  0.477
6    jideca_idec_re_23  0.455
7     jideca_dec_se_23  0.426
8     jideca_dec_re_23  0.395
9    jideca_mdec_re_23  0.295
10  jideca_idec_dnn_23  0.302
11   jideca_dec_dnn_23  0.299

In [5]:
df_ari

            parameters    ari
0   jideca_midec_re_23  0.275
1    jideca_mdec_se_23  0.277
2    jideca_idec_se_23  0.228
3   jideca_mdeca_se_23  0.239
4   jideca_midec_se_23  0.230
5    jideca_idec_re_23  0.224
6   jideca_mdeca_re_23  0.216
7     jideca_dec_se_23  0.195
8     jideca_dec_re_23  0.184
9    jideca_mdec_re_23  0.099
10  jideca_idec_dnn_23  0.057
11   jideca_dec_dnn_23  0.036

In [6]:
df_purity

            parameters  purity
0    jideca_idec_se_23   0.359
1    jideca_mdec_se_23   0.360
2    jideca_idec_re_23   0.299
3   jideca_mdeca_se_23   0.292
4   jideca_midec_re_23   0.290
5     jideca_dec_se_23   0.274
6     jideca_dec_re_23   0.246
7    jideca_mdec_re_23   0.230
8   jideca_midec_se_23   0.266
9   jideca_mdeca_re_23   0.270
10  jideca_idec_dnn_23   0.190
11   jideca_dec_dnn_23   0.187